version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    environment:
      TEST_RESULTS: "/tmp/test-results"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
            - go-mod-v1-
      - run:
          name: Setup test tools
          command: |
            cp go.sum go.sum.original
            go get github.com/jstemmer/go-junit-report
            mkdir $TEST_RESULTS
      - run:
          name: Run unit tests
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            make test | tee ${TEST_RESULTS}/go-test.out
            cat ${TEST_RESULTS}/go-test.out | go-junit-report > ${TEST_RESULTS}/go-test-report.xml
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum.original" }}
          paths:
            - "/go/pkg/mod"
      - store_test_results:
          path: /tmp/test-results

workflows:
  build:
    jobs:
      - test
