version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    environment:
      TEST_RESULTS: "/tmp/test-results"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
            - go-mod-v1-
      - run:
          name: Setup test tools
          command: |
            cp go.sum go.sum.original
            mkdir -p $TEST_RESULTS/gotest
      - run:
          name: Run unit tests
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            GOTEST="gotestsum --junitfile ${TEST_RESULTS}/gotest/results.xml --" make test
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum.original" }}
          paths:
            - "/go/pkg/mod"
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - test
